name: Build macOS App

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build CalendarMenuApp
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Build and Archive
        run: |
          xcodebuild \
            -scheme "CalendarMenuApp" \
            -project CalendarMenuApp.xcodeproj \
            -configuration Release \
            -archivePath build/CalendarMenuApp.xcarchive \
            clean archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Export Archive
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath build/CalendarMenuApp.xcarchive \
            -exportPath build/Release \
            -exportOptionsPlist exportOptions.plist
      
      - name: Create DMG
        run: |
          mkdir -p dist
          hdiutil create -volname "CalendarMenuApp" \
            -srcfolder build/Release/CalendarMenuApp.app \
            -ov -format UDZO \
            dist/CalendarMenuApp.dmg
      
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: CalendarMenuApp-dmg
          path: dist/CalendarMenuApp.dmg
          retention-days: 30
      
      - name: Upload App artifact
        uses: actions/upload-artifact@v4
        with:
          name: CalendarMenuApp-app
          path: build/Release/CalendarMenuApp.app
          retention-days: 30
